module WeatherCodeMappings
  Descriptions = {
    0 => "Clear sky",
    1 => "Mainly clear",
    2 => "Partly cloudy",
    3 => "Overcast",
    45 => "Fog",
    48 => "Depositing rime fog",
    51 => "Light intensity drizzle",
    53 => "Moderate intensity drizzle",
    55 => "Dense intensity drizzle",
    56 => "Light intensity freezing drizzle",
    57 => "Dense intensity freezing drizzle",
    61 => "Slight rain",
    63 => "Moderate rain",
    65 => "Heavy intensity rain",
    66 => "Light intensity freezing rain",
    67 => "Heavy intensity freezing rain",
    71 => "Slight intensity snow fall",
    73 => "Moderate intensity snow fall",
    75 => "Heavy intensity snow fall",
    77 => "Snow grains",
    80 => "Slight rain showers",
    81 => "Moderate rain showers",
    82 => "Violent rain showers",
    85 => "Slight snow showers",
    86 => "Heavy snow showers",
    95 => "Slight or moderate thunderstorm",
    96 => "Thunderstorm with slight hail",
    99 => "Thunderstorm with heavy hail"
  }.freeze
end